name: Cache RGBDS
description: Caches RGBDS and builds it from source if missing. Based on Cache CC65 by jroweboy (MIT)
inputs:
  rgbdsRef:
    description: "RGBDS Git Ref (used to checkout a fixed version)"
    required: false
    default: "0105779789909e2daad5aa09450dd3101aa5e723"
  rgbdsPath:
    description: "RGBDS path to cache"
    required: false
    default: ${{ github.workspace }}/opt/rgbds
runs:
  using: "composite"
  steps:
      # Cache RGBDS
      - uses: actions/cache@v3
        id: cache_rgbds
        with:
          path: ${{ inputs.rgbdsPath }}
          key: ${{ runner.os }}-rgbds-${{ inputs.rgbdsRef }}-${{ hashFiles('.github/actions/cache_rgbds/*') }}
      # Checkout RGBDS
      - uses: actions/checkout@v3
        if: steps.cache_rgbds.outputs.cache-hit != 'true'
        with:
          repository: gbdev/rgbds
          ref: ${{ inputs.rgbdsRef }}
          path: './rgbds'
      # Build RGBDS
      - if: steps.cache_rgbds.outputs.cache-hit != 'true'
        run: |
          cd rgbds
          PREFIX=${{ inputs.rgbdsPath }} make 
          PREFIX=${{ inputs.rgbdsPath }} make install
        shell: bash
      # Add RGBDS binaries to path
      - run: echo "${{ inputs.rgbdsPath }}/bin" >> $GITHUB_PATH
        shell: bash