name: build-artifact
on: push

jobs:
  nes-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install build-essential python3-pil -y

      - uses: ./.github/actions/cache_cc65
      - name: Run makefile
        run: |
          cd nes
          make 240pee.nes 240pee-bnrom.nes mdfourier.nsf mdfourier4k.nes

      - name: Upload ROM binaries
        uses: actions/upload-artifact@master
        with:
          name: 240pee-NES
          path: |
            nes/240pee.nes
            nes/240pee-bnrom.nes
            nes/mdfourier.nsf
            nes/mdfourier4k.nes
            nes/map.txt
            nes/bnmap.txt
            nes/mdfmap.txt
            nes/nsfmap.txt
  gb-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install libpng-dev python3-pil build-essential bison pkg-config -y

      - uses: ./.github/actions/cache_rgbds
      - name: Run makefile
        run: |
            cd gameboy
            make gb240p.gb

      - name: Upload ROM binaries
        uses: actions/upload-artifact@master
        with:
          name: 240pee-GB
          path: |
            gameboy/gb240p.gb
            gameboy/gb240p.map
            gameboy/gb240p.sym

  gba-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install python3-pil -y

      - name: Run makefile
        run: |
          cd gba
          make

      - name: Upload ROM binaries
        uses: actions/upload-artifact@master
        with:
          name: 240pee-GBA
          path: |
            gba/240pee_mb.gba
            gba/240pee_mb.elf
